# CIFAR-10 Split Comparison Experiment Configuration
gold_splitter:
  min_pxt_insert_size: 10000
  batch_size: 128
  num_workers: 15
  table_name: cifar10_dinov3small_224
  update_selection: True

# Experiment settings
model_type: vit # cnn, resnet, vit
split_method: gold  # Options: random, gold, or all
val_ratio: 0.3

data_dir: .data

random_state: 42

remove_ratio: 0.98
duplicate_table_path: duplicate_cifar10_dinov3small_224
drop_duplicate_table: True
to_duplicate_clusters: 2
cluster_count: 10
duplicate_per_sample: 10

random_split_state: 42

max_epochs: 100
batch_size: 256
learning_rate: 0.001
num_workers: 15
validate_on_test: True

# MLFlow settings
mlflow_tracking_uri: mlruns
mlflow_experiment_name: cifar10
mlflow_run_name: cifar10

# Debug settings
debug_count: null  # Set to a number (e.g., 5) to limit validation/test batches for debugging. null = no limit
debug_train_count: null  # Set to a number (e.g., 10) to limit training batches for debugging. null = no limit
