# feature extractor in the descriptor
model:
    _target_: hydra.utils.get_method
    path: torchvision.models.resnet18

weights: DEFAULT
layers : ["avgpool",]

# selector
reducer:
    _target_: goldener.reduce.GoldReducer
    reducer:
        _target_: sklearn.decomposition.PCA
        n_components: 3

# shared settings for data loading
batch_size: 64
num_workers: 4
